<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>mybooks.integration</RootNamespace>
    <AssemblyName>mybooks.integration</AssemblyName>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\mybooks.contracts\mybooks.contracts.csproj" />
    <ProjectReference Include="..\mybooks.eventstoreprovider\mybooks.eventstoreprovider.csproj" />
    <ProjectReference Include="..\mybooks.logic\mybooks.logic.csproj" />
  </ItemGroup>
</Project>
