<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>mybooks.eventstoreprovider</RootNamespace>
    <AssemblyName>mybooks.eventstoreprovider</AssemblyName>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NEventStore" Version="6.0.0" />
    <PackageReference Include="NEventStore.Serialization.Json" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\mybooks.contracts\mybooks.contracts.csproj" />
  </ItemGroup>
</Project>
