<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>mybooks</RootNamespace>
    <AssemblyName>mybooks</AssemblyName>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\mybooks.contracts\mybooks.contracts.csproj" />
    <ProjectReference Include="..\mybooks.eventstoreprovider\mybooks.eventstoreprovider.csproj" />
    <ProjectReference Include="..\mybooks.integration\mybooks.integration.csproj" />
    <ProjectReference Include="..\mybooks.logic\mybooks.logic.csproj" />
    <ProjectReference Include="..\mybooks.ui\mybooks.ui.csproj" />
  </ItemGroup>
</Project>
