<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>mybooks.logic</RootNamespace>
    <AssemblyName>mybooks.logic</AssemblyName>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\mybooks.contracts\mybooks.contracts.csproj" />
  </ItemGroup>
</Project>
